version: "3.3"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    container_name: postgres
    ports:
      - '5432:5432'
    volumes: 
      - ${HOME}/postgres/data:/var/lib/postgresql/data
